---
- name: Ensure taloLogger target dir exists and has proper permissions
  file: dest={{ tl_target_dir }} state=directory owner={{ tl_dir_owner }} mode=0755

- name: Ensure taloLoggerGraph target dir exists and has proper permissions
  file: dest={{ tlg_target_dir }} state=directory owner={{ tlg_dir_owner }} mode=0755

- name: Ensure taloLoggerGraph target subdir exists and has proper permissions
  file: dest={{ tlg_target_subdir }} state=directory owner={{ tlg_dir_owner }} mode=0755

- name: Ensure taloLoggerGraph execution dir exists and has proper permissions
  file: dest={{ tlg_target_dir }}/log state=directory owner={{ tlg_dir_owner }} mode=0755

- name: Retrieve taloLoggerGraph installation package
  get_url: url={{ tl_graph_download_URL }}/{{ tl_graph_package }} dest={{ tl_target_dir }}/{{ tl_graph_package }}

- name: Unzip taloLoggerGraph installation package
  unarchive: src={{ tl_target_dir }}/{{ tl_graph_package }} dest={{ tlg_target_subdir }} copy=no

- name: Copy index.php
  command: cp {{ tlg_target_subdir }}/taloLoggerGraph/index.php {{ tlg_target_dir }}/log

- name: Copy taloLoggerGraph.conf
  command: cp {{ tlg_target_subdir }}/taloLoggerGraph/taloLoggerGraph.conf {{ tlg_target_dir }}/log

- name: Create symlink to getchart.php
  file: src={{ tlg_target_subdir }}/taloLoggerGraph/taloLoggerGraph_getchart.php dest={{ tlg_target_dir }}/log/taloLoggerGraph_getchart.php state=link

- name: Install dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items: 
    - apache2
    - php5
    - libapache2-mod-php5
    - unzip
    - python-mysqldb
    - php5-mysql
    - libphp-jpgraph

- name: Set datastore as MYSQL in taloLoggerGraph.conf
  lineinfile:
    dest={{ tlg_target_dir }}/log/taloLoggerGraph.conf
    regexp='^DB_TYPE'
    line='DB_TYPE = MYSQL'

- name: Enable JavaScript charts in taloLoggerGraph.conf
  lineinfile:
    dest={{ tlg_target_dir }}/log/taloLoggerGraph.conf
    regexp='^JAVASCRIPT_CHARTS'
    line='JAVASCRIPT_CHARTS = true'

- name: Set static path for example image
  lineinfile:
    dest={{ tlg_target_dir }}/log/taloLoggerGraph.conf
    regexp='^BACKGROUND'
    line='BACKGROUND = {{ tlg_target_subdir }}/taloLoggerGraph/docs/ghp_process.png'

- name: Set permissions for web directory
  shell: 'chown -R www-data:www-data {{ tlg_target_dir }}'

- name: Add Apache2 configuration
  template:
    src=talo.conf.j2
    dest=/etc/apache2/sites-available/talo.conf
    owner=root
    group=root
    mode=0644

- name: Disable the default site
  command: a2dissite 000-default

- name: Enable talo virtualhost
  command: a2ensite talo
  notify:
    - restart httpd
